<?php
return[
    'permissions'=>[
        'products'=>'الاصناف',
        'products.create'=>'انشاء صنف جديد',
        'products.store'=>'حفظ صنف جديد',
        'products.destroy'=>'حذف صنف محدد',
        'products.update'=>'تعديل الاصناف',
        'products.edit'=>'عرض صنف محدد',
        'products.show'=>'تفاصيل الاصناف',

        'productCategories.index'=>'مجموعات الاصناف',
        'productCategories.create'=>'انشاء مجموعه اصناف جديده',
        'productCategories.store'=>'حفظ مجموعه اصناف جديدة',
        'productCategories.show'=>'تفاصيل مجموعات الاصناف',
        'productCategories.edit'=>'عرض مجموعات الاصناف',
        'productCategories.update'=>'تعديل مجموعه الاصناف',
        'productCategories.destroy'=>'حذف مجموعات الاصناف',

        'serviceCategories.index'=>'مجموعات الخدمات',
        'serviceCategories.create'=>'انشاء مجموعه الخدمات',
        'serviceCategories.store'=>'حفظ مجموعه الخدمات',
        'serviceCategories.show'=>'تفاصيل مجموعه الخدمات',
        'serviceCategories.edit'=>'عرض مجموعه الخدمات',
        'serviceCategories.update'=>'تعديل مجموعه الخدمات',
        'serviceCategories.destroy'=>'حذف مجموعه الخدمات',

        'services.index'=>'الخدمات',
        'services.create'=>'انشاء خدمات جديده',
        'services.store'=>'حفظ خدمات جديده',
        'services.show'=>'عرض تفاصيل الخدمات',
        'services.edit'=>'عرض الخدمات',
        'services.update'=>'تعديل الخدمات',
        'services.destroy'=>'حذف الخدمات',

        'serviceItems.index'=>'عناصر الخدمات',
        'serviceItems.create'=>'انشاء عنصر خدمات',
        'serviceItems.store'=>'حفظ عنصر خدمات',
        'serviceItems.show'=>'تفاصيل عناصر الخدمات',
        'serviceItems.edit'=>'عرض عناصر الخدمات',
        'serviceItems.update'=>'تعديل عناصر الخدمات',
        'serviceItems.destroy'=>'حذف عناصر الخدمات',

        'stages.index'=>'مراحل الانتاج',
        'stages.create'=>'انشاء مرحله انتاج جديده',
        'stages.store'=>'حفظ مرحله انتاج جديده',
        'stages.show'=>'تفاصيل مرحله الانتاج',
        'stages.edit'=>'عرض مرحله الانتاج',
        'stages.update'=>'تعديل مرحله الانتاج',
        'stages.destroy'=>'حذف مرحله انتاج',

        'satgeCategories.index'=>'مجموعات مراحل الانتاج',
        'satgeCategories.create'=>'انشاء مجموعة مراحل انتاج جديده',
        'satgeCategories.store'=>'حفظ مجموعة مراحل انتاج جديده',
        'satgeCategories.show'=>'تفاصيل مجموعات مراحل الانتاج',
        'satgeCategories.edit'=>'عرض مجموعات مراحل الانتاج',
        'satgeCategories.update'=>'تعديل مجموعات مراحل الانتاج',
        'satgeCategories.destroy'=>'حذف مجموعات مراحل انتاج',

        'customers.index'=>'العملاء',
        'customers.create'=>'انشاء عميل جديد',
        'customers.store'=>'حفظ عميل جديد',
        'customers.show'=>'تفاصيل بيانات العملاء',
        'customers.edit'=>'عرض بيانات العميل',
        'customers.update'=>'تعديل بيانات العميل',
        'customers.destroy'=>'حذف بيانات العميل',

        'get_receive_receipt'=>'انشاء اذن اضافة للعميل',
        'get_work_order'=>'انشاء الغسلة للعميل',


        'receiveReceipts.index'=>'اذن اضافة',
        'receiveReceipts.create'=>'إنشاء اذن اضافة جديد',
        'receiveReceipts.store'=>'حفظ اذن اضافة جديد',
        'receiveReceipts.show'=>'تفاصيل اذن اضافة',
        'receiveReceipts.edit'=>'عرض اذن اضافة',
        'receiveReceipts.update'=>'تعديل اذن اضافة',
        'receiveReceipts.destroy'=>'حذف اذن الاضافة',

        'returnReceipts.index'=>'اذن اضافة مرتجع',
        'returnReceipts.create'=>'إنشاء اذن اضافة مرتجع',
        'returnReceipts.store'=>'حفظ اذن اضافة مرتجع',
        'returnReceipts.show'=>'تفاصيل اذن اضافة المرتجع',
        'returnReceipts.edit'=>'عرض اذن اضافة المرتجع',
        'returnReceipts.update'=>'تعديل اذن اضافة المرتجع',
        'returnReceipts.destroy'=>'حذف اذن اضافة المرتجع',

        'teams.index'=>'الاقسام',
        'teams.create'=>'انشاء قسم جديد',
        'teams.store'=>'حفظ قسم جديد',
        'teams.show'=>'تفاصيل بيانات القسم',
        'teams.edit'=>'عرض القسم',
        'teams.update'=>'تعديل القسم',
        'teams.destroy'=>'حذف القسم',

        'workOrders.index'=>'الغسلات',
        'workOrders.create'=>'انشاء الغسلة جديد',
        'workOrders.store'=>'حفظ الغسلة جديد',
        'workOrders.show'=>'تفاصيل الغسلة',
        'workOrders.edit'=>'عرض الغسلة',
        'workOrders.update'=>'تعديل الغسلة',
        'workOrders.destroy'=>'حذف الغسلة',
        'workOrders.print'=>'طباعه الغسلة',
        'workOrders.print_cs'=>'طباعه الغسلة خاص بخدمة العملاء',

        


        'add_activity'=>'زرار ارسال الى مرحلة',
        'add_not'=>'زرار اضافة ملحوظة',
        'close_work_order'=>'زرار اغلاق الغسلة كلها',
        'open_work_order'=>'زرار فتح الغسلة تانى',
        'close_activity'=>'زرار اغلاق مرحلة',
        'delete_activity'=>'زرار حذف المرحلة',


        'places.index'=>'اماكن التخزين',
        'places.create'=>'انشاء مكان التخزين',
        'places.store'=>'حفظ مكان التخزين',
        'places.show'=>'تفاصيل اماكن التخزين',
        'places.edit'=>'عرض اماكن التخزين',
        'places.update'=>'تعديل اماكن التخزين',
        'places.destroy'=>'حذف اماكن التخزين',

        'receivables.index'=>'المستلمون',
        'receivables.create'=>'إنشاء مستلم جديد',
        'receivables.store'=>'حفظ مستلم جديد',
        'receivables.show'=>'تفاصيل المستلم',
        'receivables.edit'=>'عرض المستلم',
        'receivables.update'=>'تعديل المستلم',
        'receivables.destroy'=>'حذف المستلم',

        'reservations.index'=>'الغسلات المسبقة',
        'reservations.create'=>'إنشاء غسلة مسبقة',
        'reservations.store'=>'حفظ غسلة مسبقة',
        'reservations.show'=>'تأكيد حجز غسلة مسبقة',
        'reservations.edit'=>'عرض غسلة مسبقة',
        'reservations.update'=>'تعديل غسلة مسبقة',
        'reservations.destroy'=>'حذف غسلة مسبقة',

        'deliverOrders.index'=>'إذن التغليف',
        'deliverOrders.create'=>'إنشاء إذن التغليف جديد',
        'deliverOrders.store'=>'حفظ إذن التغليف جديد',
        'deliverOrders.show'=>'تفاصيل إذن التغليف',
        'deliverOrders.edit'=>'عرض إذن التغليف',
        'deliverOrders.update'=>'تعديل إذن التغليف',
        'deliverOrders.destroy'=>'حذف إذن التغليف',
        'print_barcode'=>'طباعة باركود إذن التغليف',

        'deliverOrders_finance'=>'انشاء اذن التسليم',
        'update_delivered_package'=>'زرار حفظ اذن التسليم',
        'final_deliver_orders'=> ' اذونات تسليم العملاء',
        'show_final_deliver'=>'طباعة اذن تسليم عميل',

        'deliverOrders_finance_customers'=>'انشاء اذن تسليم مجمع',
        'update_delivered_package_all'=>'زرار حفظ اذن تسليم مجمع',
        'edit_final_deliver'=>'زرار تعديل إذن التسليم',
        'delete_final_deliver_all'=>'زرار حذف إذن التسليم',

        'security_deliver'=>'تسليم الأمن',
        'add_security_deliver'=>'الأمن',
        'add_security_deliver_order'=>'تاكيد تسليم الامن',


        'followup_report'=>'تقارير متابعة الانتاج',
        'reports.index'=>'صفحة تقارير الانتاج',

        // 'accfollowup_report'=>'تقارير الحسابات',
        // 'accreports.index'=>'صفحة تقارير الحسابات',

        'readyfollowup_report'=>'تقارير مخزن الجاهز',
        'readyreports.index'=>'صفحة تقارير مخزن الجاهز',

        'residual_result'=>'تقارير البواقى',
        'residual'=>'صفحة تقارير البواقى',

        'reports_stages_result'=>'تقارير مرحلة معينة',
        'reports_stages'=>'صفحة تقارير مرحلة معينة',

        'receive_receipt_open_result'=>'تقارير اذون الاضافة المفتوحة',
        'receive_receipt_open'=>'صفحة تقارير اذون الاضافة المفتوحة',

        'models_report_result'=>'تقارير الموديلات',
        'models_report'=>'صفحة تقارير الموديلات',

        'result_balance'=>'تفاصيل تقرير الميزان',
        'result_balance_all'=>'بحث تفاصيل تقارير الميزان',

        // 'dashboard_report'=>'تقرير تحليل الاداء',
        // 'dashboard_report_result'=>'نتائج تقرير تحليل الاداء',

        'activity_logs'=>'تقرير سجل النشاطات',
        'activity_logs_result'=>'نتائج تقرير سجل النشاطات',

        'final_delivers_report'=>'تقرير اذون التسليم',
        'final_delivers_result'=>'نتائج تقرير اذون التسليم',

        
        'labSamples.index'=>'العينات',
        'labSamples.create'=>'إنشاء عينات جديدة',
        'labSamples.store'=>'حفظ عينات جديدة',
        'lab_samples.show'=>'تفاصيل العينات',
        'labSamples.print'=>'طباعة العينات',
        'labSamples.edit'=>'عرض العينات',
        'labSamples.update'=>'تعديل العينات',
        'labSamples.destroy'=>'حذف العينات',
        'labSamples_lab_view'=>'صفحة العينات الخاصة بالمعمل',
        'labViewfollow'=>'زرار يفتح مرحلة على المعمل',
        'labReadySample'=>'زار يفتح تشغيل العينة فى المعمل',
        'labRecieveCheck'=>'زار تحقق لاستلام العينة فى المعمل',
        'labCloseSample'=>'زار يقفل العينة على المعمل',
        'labConfirmSample'=>'زرار يأكد استلام العينة من خدمة العملاء',
        'labReadySample_view'=>'صفحة عينات جاهزة للتسليم',
        'labDeliverSample'=>'زرار تسليم للعميل',
        'tab_index'=>'صفحة كل العينات',
        'tab_all'=>'زراير فلتر لكل العينات',
        'return_sample_to_lab'=>'زرار رجوع العينة الى المعمل',
        
        'createSamples.index'=>'الرسبى',
        'createSamples.create'=>'انشاء رسبى',
        'createSamples.store'=>'حفظ رسبى',
        'createSamples.show'=>'تفاصيل الرسبى',
        'createSamples.edit'=>'عرض الرسبى',
        'createSamples.update'=>'تعديل الرسبى',
        'createSamples.destroy'=>'حذف الرسبى',
        
        'fabricSources.index'=>'مصادر القماش',
        'fabricSources.create'=>'انشاء مصدر القماش',
        'fabricSources.store'=>'حفظ مصدر القماش',
        'fabricSources.show'=>'تفاصيل مصدر القماش',
        'fabricSources.edit'=>'عرض مصدر القماش',
        'fabricSources.update'=>'تعديل مصدر القماش',
        'fabricSources.destroy'=>'حذف مصدر القماش',
        
        'fabrics.index'=>'القماش',
        'fabrics.create'=>'انشاء قماشة',
        'fabrics.store'=>'حفظ قماشة',
        'fabrics.show'=>'تفاصيل قماشة',
        'fabrics.edit'=>'عرض قماشة',
        'fabrics.update'=>'تعديل قماشة',
        'fabrics.destroy'=>'حذف قماشة',


        'invUnits.index'=>'الوحدات',
        'invUnits.create'=>'انشاء الوحدات',
        'invUnits.store'=>'حفظ الوحدات',
        'invUnits.show'=>'تفاصيل الوحدات',
        'invUnits.edit'=>'عرض الوحدات',
        'invUnits.update'=>'تعديل الوحدات',
        'invUnits.destroy'=>'حذف الوحدات',

        'invCategories.index'=>'المجموعات',
        'invCategories.create'=>'انشاء المجموعات',
        'invCategories.store'=>'حفظ المجموعات',
        'invCategories.show'=>'تفاصيل المجموعات',
        'invCategories.edit'=>'عرض المجموعات',
        'invCategories.update'=>'تعديل المجموعات',
        'invCategories.destroy'=>'حذف المجموعات',

        'invProducts.index'=>'المنتجات',
        'invProducts.create'=>'انشاء المنتجات',
        'invProducts.store'=>'حفظ المنتجات',
        'invProducts.show'=>'تفاصيل المنتجات',
        'invProducts.edit'=>'عرض المنتجات',
        'invProducts.update'=>'تعديل المنتجات',
        'invProducts.destroy'=>'حذف المنتجات',


        'invStores.index'=>'المخازن',
        'invStores.create'=>'انشاء المخازن',
        'invStores.store'=>'حفظ المخازن',
        'invStores.show'=>'تفاصيل المخازن',
        'invStores.edit'=>'عرض المخازن',
        'invStores.update'=>'تعديل المخازن',
        'invStores.destroy'=>'حذف المخازن',
        
        'colorCategories.index'=>'مجموعه الالوان',
        'colorCategories.create'=>'انشاء مجموعه الالوان جديدة',
        'colorCategories.store'=>'حفظ مجموعه الالوان',
        'colorCategories.show'=>'تفاصيل مجموعه الالوان',
        'colorCategories.edit'=>'عرض مجموعه الالوان',
        'colorCategories.update'=>'تعديل مجموعه الالوان',
        'colorCategories.destroy'=>'حذف مجموعه الالوان',

        'colorCodes.index'=>'اكواد الالوان',
        'colorCodes.create'=>'انشاء اكواد الالوان',
        'colorCodes.store'=>'حفظ اكواد الالوان',
        'colorCodes.show'=>'تفاصيل اكواد الالوان',
        'colorCodes.edit'=>'عرض اكواد الالوان',
        'colorCodes.update'=>'تعديل اكواد الالوان',
        'colorCodes.destroy'=>'حذف اكواد الالوان',

        'colors.index'=>'الالوان',
        'colors.create'=>'انشاء لون جديد',
        'colors.store'=>'حفظ اللون',
        'colors.show'=>'تفاصيل الالوان',
        'colors.edit'=>'عرض الالوان',
        'colors.update'=>'تعديل اللون',
        'colors.destroy'=>'حذف اللون',


        'invImportOrders.index'=>'اذن استلام بضاعة',
        'invImportOrders.create'=>'انشاء اذن استلام بضاعة',
        'invImportOrders.store'=>'حفظ اذن استلام بضاعة',
        'invImportOrders.show'=>'تفاصيل اذن استلام بضاعة',
        'invImportOrders.edit'=>'عرض اذن استلام بضاعة',
        'invImportOrders.update'=>'تعديل اذن استلام بضاعة',
        'invImportOrders.destroy'=>'حذف اذن استلام بضاعة',

        'insert_into_stores'=>'الموافقة على الاضافة بالمخزن',

        'invExportOrders.index'=>'اذن الصرف',
        'invExportOrders.create'=>'انشاء اذن الصرف',
        'invExportOrders.store'=>'حفظ اذن الصرف',
        'invExportOrders.show'=>'تفاصيل اذن الصرف',
        'invExportOrders.edit'=>'عرض اذن الصرف',
        'invExportOrders.update'=>'تعديل اذن الصرف',
        'invExportOrders.destroy'=>'حذف اذن الصرف',

        'invStockTransfers.index'=>'اذن التحويل',
        'invStockTransfers.create'=>'انشاء اذن التحويل',
        'invStockTransfers.store'=>'حفظ اذن التحويل',
        'invStockTransfers.show'=>'تفاصيل اذن التحويل',
        'invStockTransfers.edit'=>'عرض اذن التحويل',
        'invStockTransfers.update'=>'تعديل اذن التحويل',
        'invStockTransfers.destroy'=>'حذف اذن التحويل',
        'invStockTransfers.confirm_transfer'=>'موافقةالتحويل من المخزن',

        'suppliers.index'=>'الموردين',
        'suppliers.create'=>'انشاء مورد جديد',
        'suppliers.store'=>'حفظ مورد جديد',
        'suppliers.show'=>'تفاصيل بيانات الموردين',
        'suppliers.edit'=>'عرض بيانات الموردين',
        'suppliers.update'=>'تعديل بيانات الموردين',
        'suppliers.destroy'=>'حذف بيانات الموردين',
        
        'product_report'=>'كارته صنف المنتجات',
        'product_report_result'=>'عرض كارته صنف المنتجات',
        // 'total_Products_report'=>'اجمالي رصيد مخزن المستلزمات',
        // 'total_Products_report_result'=>'عرض اجمالي رصيد مخزن المستلزمات',

        'roles.index'=>'الصلاحيات',
        'roles.create'=>'انشاء الصلاحيات',
        'roles.store'=>'حفظ الصلاحيات',
        'roles.show'=>'تفاصيل الصلاحيات',
        'roles.edit'=>'عرض الصلاحيات',
        'roles.update'=>'تعديل الصلاحيات',
        'roles.destroy'=>'حذف الصلاحيات',

        'users.index'=>'المستخدمين',
        'users.create'=>'انشاء المستخدمين',
        'users.store'=>'حفظ المستخدمين',
        'users.show'=>'تفاصيل المستخدمين',
        'users.edit'=>'عرض المستخدمين',
        'users.update'=>'تعديل المستخدمين',
        'users.destroy'=>'حذف المستخدمين',



        'important_workOrders'=>'زرار استعجال الغسلة',


        'product_price'=>'التسعير',
        'product_price.production'=>'تسعير المنتجات',
        // 'product_price.final_product_price'=>'تسعير المنتج التام',
        'product_price.edit_final_product_price'=>'تعديل اسعار المنتجات ',

        'treasuries.index'=>'الخزينه',
        'treasuries.create'=>'انشاء الخزينه',
        'treasuries.store'=>'حفظ الخزينه',
        'treasuries.show'=>'تفاصيل الخزينه',
        'treasuries.edit'=>'عرض الخزينه',
        'treasuries.update'=>'تعديل الخزينه',
        'treasuries.destroy'=>'حذف الخزينه',
  
  
        // 'paymentTypes.index'=>'نوع الدفع',
        // 'paymentTypes.create'=>'انشاء نوع الدفع',
        // 'paymentTypes.store'=>'حفظ نوع الدفع',
        // 'paymentTypes.show'=>'تفاصيل نوع الدفع',
        // 'paymentTypes.edit'=>'عرض نوع الدفع',
        // 'paymentTypes.update'=>'تعديل نوع الدفع',
        // 'paymentTypes.destroy'=>'حذف نوع الدفع',
  
        'banks.index'=>'البنوك',
        'banks.create'=>'انشاء البنوك',
        'banks.store'=>'حفظ البنوك',
        'banks.show'=>'تفاصيل البنوك',
        'banks.edit'=>'عرض البنوك',
        'banks.update'=>'تعديل البنوك',
        'banks.destroy'=>'حذف البنوك',
  
        'treasuryDetails.index'=>'يومية الخزينة',
        'treasuryDetails.create'=>'انشاء يومية الخزينه',
        'treasuryDetails.store'=>'حفظ يومية الخزينه',
        'treasuryDetails.show'=>'تفاصيل يومية الخزينه',
        'treasuryDetails.edit'=>'عرض يومية الخزينه',
        'treasuryDetails.update'=>'تعديل يومية الخزينه',
        'treasuryDetails.destroy'=>'حذف يومية الخزينه',
        'treasuryDetails.treasury_journal'=>'جدول يومية الخزينه',
        'treasuryDetails.under_collection'=>'اوراق تحت التحصيل',
        'treasuryDetails.check_approved'=>'تحصيل الشيك',
        'treasuryDetails.check_reject'=>'رفض الشيك',
        'treasuryDetails.add_discount_customer'=>'اضافة خصم للعميل',
        'treasuryDetails.edit_discount_customer'=>'تعديل خصم للعميل',
        'treasuryDetails.delete_discount'=>'حذف خصم للعميل',
        'treasuryDetails.add_account_settlement_customer'=>'اضافة تسوية للعميل',
        'treasuryDetails.edit_account_settlement_customer'=>'تعديل تسوية للعميل',
        'treasuryDetails.delete_settlement'=>'حذف تسوية للعميل',
        

        'accounting'=>'الحسابات',
        'accountingCosts.index'=>'التكاليف',
        'accountingCosts.create'=>'انشاء التكاليف',
        'accountingCosts.store'=>'حفظ التكاليف',
        'accountingCosts.show'=>'تفاصيل التكاليف',
        // 'accountingCosts.edit'=>'عرض التكاليف',
        // 'accountingCosts.update'=>'تعديل التكاليف',
        'accountingCosts.destroy'=>'حذف التكاليف',


        'invoices'=>'الفواتير',
        'invoices.index'=>'الفواتير',
        'invoices.create'=>'انشاء الفواتير',
        'invoices.store'=>'حفظ الفواتير',
        'invoices.show'=>'تفاصيل الفواتير',
        'invoices.edit'=>'عرض الفواتير',
        'invoices.update'=>'تعديل الفواتير',
        'invoices.destroy'=>'حذف الفواتير',

        'report1'=>'تقارير مبيعات',
        'report1.customer_account_report'=>'تقرير حساب العملاء',
        'report1.supplier_account_report'=>'تقرير حساب الموردين',
        'report1.treasuries_report'=>'تقرير يوميه خزينه',
        'report1.customer_invoices_analysis'=>'تقرير تحليل العملاء',
        'report1.invoice_report'=>'تقرير المبيعات',
        'report1.service_prices_report'=>'تقرير الخدمات المباعة',

        'report2'=>'تقارير مخازن',
        'report2.product_report'=>'تقرير كارته صنف المنتجات',
        'report2.total_Products_report'=>'اجمالي رصيد مخزن المستلزمات',
        'report2.model_reports'=>'تقرير بيان الاوردرات',
  
    ]
]
?>
